project:
  type: seedcase-theme

website:
  title: "Seedcase Project: Decisions Archive"
  site-url: "https://decisions.seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/decisions"
  navbar:
    title: false
    logo: "_extensions/seedcase-project/seedcase-theme/logos/docs/navbar-decisions.svg"
    logo-alt: "Seedcase Decisions logo: Main page"
    pinned: true
    left:
      - current.qmd
      - previous.qmd
    right:
      - text: "<img src='/_extensions/seedcase-project/seedcase-theme/logos/seedcase/a-part-of.svg' alt='Main Seedcase website' height='30px'>"
        href: "https://seedcase-project.org"
    tools:
      - icon: github
        href: "https://github.com/seedcase-project/decisions"
        aria-label: "GitHub icon: Source repository"

format:
  seedcase-theme-html:
    include-before-body:
      - "includes/site-counter.html"
