---
title: ""
description: "Our reasons for ..."
date: ""
categories:
---

::: content-hidden
Use other decision posts as inspiration to writing these.
Leave the content-hidden sections in the text for future reference.
:::

## Context and problem statement

::: content-hidden
State the context and some background on the issue, then write the
problem statement in the form of a question.
:::

## Decision drivers

::: content-hidden
List the main reasons for why we are making this decision, including any
issues that have arisen and that directly impact our work.
:::

## Considered options

::: content-hidden
List and describe some of the options, as well as some of the benefits
and drawbacks for each option.
:::

### Option 1

::: {.columns}
::: {.column}
#### Benefits

::: content-hidden
List the main benefits and drawbacks with a short description.
These should be of relevance for us but written in general form about the option,
rather than how it impacts us specifically
(the latter will be elaborated upon in the section "Consequences").
:::

- Item 1

:::
::: {.column}

#### Drawbacks

- Item 1

:::
:::

## Decision outcome

::: content-hidden
Describe which decision was made. Use the form "We decided on CHOICE because of
REASONS."
:::

### Consequences

::: content-hidden
Elaborate on how the decision will impact us.
This section often includes comments on the drawbacks,
e.g. detailing how we could adapt to a new tool
or explaining why a particular drawback is not a major concern for us.
:::

## Resources used for this post

::: content-hidden
List the resources used to write this post.
:::
